# Generated by Django 3.2.18 on 2023-04-20 08:55

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20230420_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(default=webapp.models.generate_key_doctor, editable=False, primary_key=True, serialize=False),
        ),
    ]
