# Generated by Django 3.2.18 on 2023-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20230420_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorkey',
            name='key',
            field=models.IntegerField(default=1),
        ),
    ]
