# Generated by Django 3.2.18 on 2023-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_doctorkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='positive',
            field=models.IntegerField(default=0),
        ),
    ]
